### ISSUE TITLE
scheduled run failed

### ISSUE THREAD

**Issue by nhomble** [nhomble/feed-cli#8]
```
cat feeds/general | go run github.com/nhomble/feed-cli -templateOverride sub.tpl > general.html
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x63a1a0]

goroutine 24 [running]:
net/url.validEncoded(0x8, 0x3608080858aaaedc, 0x1, 0xc00055bcb0)
	/opt/hostedtoolcache/go/1.15.8/x64/src/net/url/url.go:723 +0x40
net/url.(*URL).EscapedPath(0x878860, 0xc00055bd40, 0xc00055bcb0)
	/opt/hostedtoolcache/go/1.15.8/x64/src/net/url/url.go:701 +0x14c
net/url.(*URL).ResolveReference(0x878860, 0xc00055bcb0, 0xc00055bcb0)
	/opt/hostedtoolcache/go/1.15.8/x64/src/net/url/url.go:1075 +0x278
github.com/mmcdole/gofeed/internal/shared.(*XMLBase).push(0xc00025e5c0, 0x0, 0x0, 0x0, 0x4)
	/home/runner/go/src/github.com/mmcdole/gofeed/internal/shared/xmlbase.go:148 +0x1d8
github.com/mmcdole/gofeed/internal/shared.(*XMLBase).NextTag(0xc00025e5c0, 0xc0004922d0, 0x0, 0x0, 0x1)
	/home/runner/go/src/github.com/mmcdole/gofeed/internal/shared/xmlbase.go:109 +0xe9
github.com/mmcdole/gofeed/atom.(*Parser).parseEntry(0xc0000b2230, 0xc0004922d0, 0xc00030428b, 0x5, 0x0)
	/home/runner/go/src/github.com/mmcdole/gofeed/atom/parser.go:224 +0x174
github.com/mmcdole/gofeed/atom.(*Parser).parseRoot(0xc0000b2230, 0xc0004922d0, 0x2, 0x0, 0x0)
	/home/runner/go/src/github.com/mmcdole/gofeed/atom/parser.go:170 +0xa17
github.com/mmcdole/gofeed/atom.(*Parser).Parse(0xc0000b2230, 0x9bc700, 0xc000214aa0, 0x8c2640, 0xc000214a01, 0xc000214aa0)
	/home/runner/go/src/github.com/mmcdole/gofeed/atom/parser.go:50 +0xf0
github.com/mmcdole/gofeed.(*Parser).parseAtomFeed(0xc000080370, 0x9bc700, 0xc000214aa0, 0xc000127d10, 0xc000214a80, 0x7bc000)
	/home/runner/go/src/github.com/mmcdole/gofeed/parser.go:133 +0x47
github.com/mmcdole/gofeed.(*Parser).Parse(0xc000080370, 0x7f4ff4357320, 0xc0004aa330, 0x7f4ff4357320, 0xc0004aa330, 0x24)
	/home/runner/go/src/github.com/mmcdole/gofeed/parser.go:73 +0x279
github.com/mmcdole/gofeed.(*Parser).ParseURLWithContext(0xc000080370, 0xc000547770, 0x24, 0x9c56e0, 0xc0004a9500, 0x0, 0x0, 0x0)
	/home/runner/go/src/github.com/mmcdole/gofeed/parser.go:123 +0x432
github.com/nhomble/feed-cli/jobs.goFeedParser.parse(0xc000080370, 0xc000547770, 0x24, 0x5, 0x44c1ff2520000, 0xdf8475800, 0x0, 0x0, 0x0)
	/home/runner/go/src/github.com/nhomble/feed-cli/jobs/parser.go:28 +0xd6
github.com/nhomble/feed-cli/jobs.worker(0xc0000ae890)
	/home/runner/go/src/github.com/nhomble/feed-cli/jobs/runner.go:39 +0x129
created by github.com/nhomble/feed-cli/jobs.process
	/home/runner/go/src/github.com/nhomble/feed-cli/jobs/runner.go:30 +0x78
```

**Comment by nhomble** [comment]
https://github.com/mmcdole/gofeed/issues/160
